### ISSUE TITLE
Missing pages in KTX Spec

### ISSUE THREAD

**Issue by KhronosWebservices** [KhronosGroup/KTX-Registry#5]
The following pages are missing in the KTX registry:

| Resource                                                         | HTTP Status Code | Found on pages - Page                                          | Found on pages - Found in  |
| :--------------------------------------------------------------- | :--------------- | :------------------------------------------------------------- | :------------------------- |
| https://www.khronos.org/registry/KTX/specs/1.0/refsOESCPT        | 404 Not found    | https://www.khronos.org/registry/KTX/specs/1.0/ktxspec_v1.html | <a>                        |
| https://www.khronos.org/registry/KTX/specs/1.0/refsOESCPT        | 404 Not found    | https://www.khronos.org/registry/KTX/specs/1.0/ktxspec_v1.html | <a>                        |
| https://www.khronos.org/registry/KTX/specs/1.0/refsOESCPT        | 404 Not found    | https://www.khronos.org/registry/KTX/specs/1.0/ktxspec_v1.html | <a>                        |
| https://www.khronos.org/registry/KTX/specs/2.0/ktx-frag.html     | 404 Not found    | https://www.khronos.org/registry/KTX/specs/2.0/ktxspec_v2.html | <a>                        |
| https://www.khronos.org/registry/KTX/specs/1.0/www.imgtec.com    | 404 Not found    | https://www.khronos.org/registry/KTX/specs/1.0/ktxspec_v1.html | <a>                        |
| https://www.khronos.org/registry/KTX/specs/icons/ktx_favicon.ico | 404 Not found    | https://www.khronos.org/registry/KTX/specs/ktx_frag.html       | <link rel='shortcut icon'> |

**Comment by MarkCallow** [comment]
I've fixed the broken links in `ktxspec_v1.html`. We will soon be releasing an update to `ktxspec_v2.html` and I prefer to wait until that to fix the remaining 2 broken links.

Is it possible to put a redirect in the registry. Part of the resolution for the broken `ktx-frag.html` link in `ktxspec_v2.html` involves moving the file into the 2.0 directory. Can I add a redirect by adding something to this repo or is it something that needs to be added manually to the registry?

**Comment by KhronosWebservices** [comment]
A redirect is now in place for ktx-frag.html. All of the above broken links are now working correctly.
